# Creating a Logistic Regression to predict Absenteeism

## Import the relevant libraries

In [2]:
import pandas as pd
import numpy as np

## Load the data

In [3]:
data_preprocessed = pd.read_csv('absenteeism_preprocessed.csv')
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0               30          0         2    1                          4  
1               31          0         1    0                          0  
2               31          0         0    0                          2  
3               24          0         2    0                          4  
4               30          0         2    1                          2

## Create the targets

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0               30          0         2    1                          4   
1               31          0         1    0                          0   
2               31          0         0    0                          2   
3               24          0         2    0                          4   
4               30          0         2    1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

## A comment on the targets

In [7]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [80]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours', 'Day of the Week', 'Daily Work Load Average', 'Distance to Work'], axis = 1)

In [81]:
data_with_targets is data_preprocessed

False

In [82]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pet  \
0                     289   33               30          0         2    1   
1                     118   50               31          0         1    0   
2                     179   38               31          0         0    0   
3                     279   39               24          0         2    0   
4                     289   33               30          0         2    1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

## Select the inputs for the regression

In [83]:
data_with_targets.shape

(700, 12)

In [84]:
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
5           0         0         0         1           10   
6           0         0         0         1            7   
7           0         0         0         1            7   
8           0         0         1         0            6   
9           0         0         0         1            7   
10          1         0         0         0            7   
11          1         0         0         0            7   
12          1         0         0         0            7   
13          1         0         0         0            7   
14          0         0         0         1            7   
15          1         0         0         0            7   
16          0         0         0         1            7   
17          0         0         1         0            7   
18          1         0         0         0            7   
19          0         0         0         1            5   
20          1         0         0         0           12   
21          1         0         0         0            3   
22          1         0         0         0           10   
23          0         0         0         1            8   
24          0         0         1         0            8   
25          0         0         0         1            8   
26          0         0         0         1            4   
27          0         0         0         1           12   
28          0         0         1         0            8   
29          0         0         0         1            8   
..        ...       ...       ...       ...          ...   
670         0         0         0         1            4   
671         0         0         1         0            4   
672         1         0         0         0            4   
673         0         0         0         1            4   
674         0         0         0         1            7   
675         0         0         1         0            9   
676         0         0         0         1            9   
677         1         0         0         0            9   
678         0         0         0         1            9   
679         1         0         0         0           10   
680         0         0         0         1           10   
681         1         0         0         0           10   
682         0         0         1         0           11   
683         0         0         0         1           11   
684         0         0         0         1           11   
685         0         0         0         1            5   
686         1         0         0         0            5   
687         0         0         0         1            5   
688         0         0         0         0            5   
689         0         0         0         1            5   
690         0         0         0         0            5   
691         0         1         0         0            5   
692         1         0         0         0            5   
693         1         0         0         0            5   
694         0         0         0         1            5   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pet  
0                       289   33               30          0         2    1  
1                       118   50               31          0         1    0  
2                       179   38               31 

In [85]:
unscaled_inputs = data_with_targets.iloc[:,:-1] 

## Standardize the data

In [86]:
# from sklearn.preprocessing import StandardScaler

# absenteeism_scaler = StandardScaler()

In [87]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin):
    def __init__(self, columns, copy=True, with_mean=True, with_std=True):
        self.scaler = StandardScaler(copy, with_mean, with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [88]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [93]:
columns_to_scale = ['Month Value','Transportation Expense',
       'Age', 'Body Mass Index', 'Education', 'Children', 'Pet']

In [94]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [95]:
absenteeism_scaler.fit(unscaled_inputs)

C:\Users\jonat\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)


CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age', 'Body Mass Index', 'Education', 'Children', 'Pet'],
       copy=None, with_mean=None, with_std=None)

In [96]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

C:\Users\jonat\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.


In [97]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1     0.030796   
1           0         0         0         0     0.030796   
2           0         0         0         1     0.030796   
3           1         0         0         0     0.030796   
4           0         0         0         1     0.030796   
5           0         0         0         1     0.929019   
6           0         0         0         1     0.030796   
7           0         0         0         1     0.030796   
8           0         0         1         0    -0.268611   
9           0         0         0         1     0.030796   
10          1         0         0         0     0.030796   
11          1         0         0         0     0.030796   
12          1         0         0         0     0.030796   
13          1         0         0         0     0.030796   
14          0         0         0         1     0.030796   
15          1         0         0         0     0.030796   
16          0         0         0         1     0.030796   
17          0         0         1         0     0.030796   
18          1         0         0         0     0.030796   
19          0         0         0         1    -0.568019   
20          1         0         0         0     1.527833   
21          1         0         0         0    -1.166834   
22          1         0         0         0     0.929019   
23          0         0         0         1     0.330204   
24          0         0         1         0     0.330204   
25          0         0         0         1     0.330204   
26          0         0         0         1    -0.867426   
27          0         0         0         1     1.527833   
28          0         0         1         0     0.330204   
29          0         0         0         1     0.330204   
..        ...       ...       ...       ...          ...   
670         0         0         0         1    -0.867426   
671         0         0         1         0    -0.867426   
672         1         0         0         0    -0.867426   
673         0         0         0         1    -0.867426   
674         0         0         0         1     0.030796   
675         0         0         1         0     0.629611   
676         0         0         0         1     0.629611   
677         1         0         0         0     0.629611   
678         0         0         0         1     0.629611   
679         1         0         0         0     0.929019   
680         0         0         0         1     0.929019   
681         1         0         0         0     0.929019   
682         0         0         1         0     1.228426   
683         0         0         0         1     1.228426   
684         0         0         0         1     1.228426   
685         0         0         0         1    -0.568019   
686         1         0         0         0    -0.568019   
687         0         0         0         1    -0.568019   
688         0         0         0         0    -0.568019   
689         0         0         0         1    -0.568019   
690         0         0         0         0    -0.568019   
691         0         1         0         0    -0.568019   
692         1         0         0         0    -0.568019   
693         1         0         0         0    -0.568019   
694         0         0         0         1    -0.568019   
695         1         0         0         0    -0.568019   
696         1         0         0         0    -0.568019   
697         1         0         0         0    -0.568019   
698         0         0         0         1    -0.568019   
699         0         0         0         1    -0.568019   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431  -0.447980  0.880469   
1                 -1.574681  2.130803         1.002633  -0.447980 -0.019280   
2                 -0.654143  0.248310         1

In [98]:
scaled_inputs.shape

(700, 11)

## Split the data into train & test and shuffle

### Import the relevant module

In [99]:
from sklearn.model_selection import train_test_split

### Split

In [100]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20)

C:\Users\jonat\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [101]:
print(x_train.shape, y_train.shape)

(560, 11) (560,)


In [102]:
print(x_test.shape, y_test.shape)

(140, 11) (140,)


## Logistic Regression with sklearn

In [103]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

### Training the model

In [104]:
reg = LogisticRegression()

In [105]:
reg.fit(x_train, y_train)

C:\Users\jonat\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [106]:
reg.score(x_train, y_train)

0.775

### Manually check the accuracy

In [107]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [108]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [109]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [110]:
np.sum((model_outputs==y_train))

434

In [111]:
model_outputs.shape[0]

560

In [112]:
np.sum((model_outputs==y_train)) / model_outputs.shape[0]

0.775

## Finding the intercepts

In [113]:
reg.intercept_

array([-1.47072937])

In [114]:
reg.coef_

array([[ 2.59769035,  0.84084545,  2.93637494,  0.63263326,  0.00558681,
         0.61934164, -0.17640849,  0.2842074 , -0.09802627,  0.35192912,
        -0.27364049]])

In [115]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [116]:
feature_names = unscaled_inputs.columns.values

In [117]:
summary_table = pd.DataFrame(columns=['Feature name'], data = feature_names)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0                 Reason_1     2.597690
1                 Reason_2     0.840845
2                 Reason_3     2.936375
3                 Reason_4     0.632633
4              Month Value     0.005587
5   Transportation Expense     0.619342
6                      Age    -0.176408
7          Body Mass Index     0.284207
8                Education    -0.098026
9                 Children     0.351929
10                     Pet    -0.273640

In [118]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                Intercept    -1.470729
1                 Reason_1     2.597690
2                 Reason_2     0.840845
3                 Reason_3     2.936375
4                 Reason_4     0.632633
5              Month Value     0.005587
6   Transportation Expense     0.619342
7                      Age    -0.176408
8          Body Mass Index     0.284207
9                Education    -0.098026
10                Children     0.351929
11                     Pet    -0.273640

## Interpreting the Coefficients

In [119]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [120]:
summary_table

Feature name  Coefficient  Odds_ratio
0                Intercept    -1.470729    0.229758
1                 Reason_1     2.597690   13.432677
2                 Reason_2     0.840845    2.318326
3                 Reason_3     2.936375   18.847399
4                 Reason_4     0.632633    1.882561
5              Month Value     0.005587    1.005602
6   Transportation Expense     0.619342    1.857705
7                      Age    -0.176408    0.838275
8          Body Mass Index     0.284207    1.328708
9                Education    -0.098026    0.906625
10                Children     0.351929    1.421808
11                     Pet    -0.273640    0.760605

In [121]:
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
3                 Reason_3     2.936375   18.847399
1                 Reason_1     2.597690   13.432677
2                 Reason_2     0.840845    2.318326
4                 Reason_4     0.632633    1.882561
6   Transportation Expense     0.619342    1.857705
10                Children     0.351929    1.421808
8          Body Mass Index     0.284207    1.328708
5              Month Value     0.005587    1.005602
9                Education    -0.098026    0.906625
7                      Age    -0.176408    0.838275
11                     Pet    -0.273640    0.760605
0                Intercept    -1.470729    0.229758

Feature isn't important if coefficient is around 0 or odds ratio is around 1.

A weight of 0 implies that no matter the feature value, we will multiply it by 0 (in the model)

For a unit change in the standardized feature, the odds increase by a multiple equal to the odds ratio (1 = no change)

* Reason 0 = No reason
* Reason 1 = Various diseases
* Reason 2 = pregnancy and giving birth
* Reason 3 = poisoning
* Reason 4 = light diseases

## Test the Model

In [122]:
reg.score(x_test, y_test)

0.7357142857142858

In [123]:
predict_prob = reg.predict_proba(x_test)
predict_prob

array([[0.75306909, 0.24693091],
       [0.60933987, 0.39066013],
       [0.48594824, 0.51405176],
       [0.75524002, 0.24475998],
       [0.08399874, 0.91600126],
       [0.30189304, 0.69810696],
       [0.30166553, 0.69833447],
       [0.11508708, 0.88491292],
       [0.73775515, 0.26224485],
       [0.75400107, 0.24599893],
       [0.50725162, 0.49274838],
       [0.19728599, 0.80271401],
       [0.06163655, 0.93836345],
       [0.70895125, 0.29104875],
       [0.29283186, 0.70716814],
       [0.52394081, 0.47605919],
       [0.50683352, 0.49316648],
       [0.50892391, 0.49107609],
       [0.36710468, 0.63289532],
       [0.06355852, 0.93644148],
       [0.73645858, 0.26354142],
       [0.75524002, 0.24475998],
       [0.47452254, 0.52547746],
       [0.47285445, 0.52714555],
       [0.22021908, 0.77978092],
       [0.73807864, 0.26192136],
       [0.51193081, 0.48806919],
       [0.87673721, 0.12326279],
       [0.23439205, 0.76560795],
       [0.75524002, 0.24475998],
       [0.

In [125]:
predict_prob.shape

(140, 2)

In [126]:
predict_prob[:,1]

array([0.24693091, 0.39066013, 0.51405176, 0.24475998, 0.91600126,
       0.69810696, 0.69833447, 0.88491292, 0.26224485, 0.24599893,
       0.49274838, 0.80271401, 0.93836345, 0.29104875, 0.70716814,
       0.47605919, 0.49316648, 0.49107609, 0.63289532, 0.93644148,
       0.26354142, 0.24475998, 0.52547746, 0.52714555, 0.77978092,
       0.26192136, 0.48806919, 0.12326279, 0.76560795, 0.24475998,
       0.38906856, 0.7158631 , 0.70056896, 0.49358459, 0.24475998,
       0.59541198, 0.26256861, 0.78565518, 0.43686254, 0.604478  ,
       0.2444509 , 0.49911937, 0.26127513, 0.44806935, 0.80688538,
       0.6084217 , 0.72250109, 0.24537893, 0.24849891, 0.24414209,
       0.50246481, 0.32700139, 0.69810696, 0.24694031, 0.82061487,
       0.39145679, 0.90718611, 0.26701353, 0.35898854, 0.35937355,
       0.70417845, 0.69916351, 0.26799682, 0.78121379, 0.24619926,
       0.24661998, 0.0906395 , 0.26289262, 0.76741323, 0.29243128,
       0.26062994, 0.35373347, 0.88318587, 0.43603969, 0.59379